#+TITLE: examples of ox-s9y usage

* basic formatting

Most normal Org formatting like *bold* =code= /italic/ +striketrough+
_underline_ as well as sections and headlines should work out of the box.

Unimplemented element types should throw an error pointing to their
missing implementation.

* source code blocks

Source code using =#+BEGIN_SRC= / =#+END_SRC= will be rendered as a
=[geshi]= code block.

The source language will be copied to the geshi tag.  Some mappings
are needed, see =(org-s9y--map-to-geshi-language)= and expand
accordingly if you miss anything.

** input

#+INCLUDE: "testing/test-geshi-block.input" src org

** output

#+INCLUDE: "testing/test-geshi-block.output" src html

* foldable =<details>= blocks

Use a headline tagged with =:details:= to generate a foldable HTML
=<details>= block.  The =<details>= is closed by default.  The
headline title will be used as a =<summary>= and can contain markup.

=<details>= blocks may be nested.

The =<details>= block will end at the next headline of the same or
higher level.  To end the block early, insert a special headline with
the title =END= (also tagged as =:details:=).  While this will end the
=<details>= block, the =END= headline will not show up in the output.

** input

#+INCLUDE: "testing/test-details-complex.input" src org

** output

#+INCLUDE: "testing/test-details-complex.output" src html

* block quotes

Quote blocks using =#+BEGIN_QUOTE= / =#+END_QUOTE= will be rendered as
an HTML =<blockquote>= tag.

** input

#+INCLUDE: "testing/test-quote-block.input" src org

** output

#+INCLUDE: "testing/test-quote-block.output" src html

* entities

Use =\ast{}= to export verbatim asterisks when =*= would activate bold
formatting.

Other [[https://orgmode.org/manual/Special-Symbols.html][Org entities]] should also work.

** input

#+INCLUDE: "testing/test-entity.input" src org

** output

#+INCLUDE: "testing/test-entity.output" src html
