---
version: 2.1
commands:
  testsuite:
    steps:
      - checkout
      - run:
          name: Log Emacs Version
          command: emacs --version
      - run:
          name: Log Org Version
          command: emacs -Q --batch -f org-version
      - run:
          name: Byte compilation
          command: emacs -Q --batch -f batch-byte-compile ox-s9y.el
      - run:
          name: Tests
          command: emacs -Q --batch -l ert -l ox-s9y.elc -l testing/test-ox-s9y.el -f ert-run-tests-batch-and-exit
      - run:
          name: Lint
          command: |
            # workaround for too strict package-lint check:
            sed -i~ -e s/org-export-s9y/ox-s9y/ ox-s9y.el
            emacs -Q --batch --eval "(progn \
              (require 'package) \
              (push '(\"melpa\" . \"https://melpa.org/packages/\") package-archives) \
              (package-initialize) \
              (unless package-archive-contents \
                 (package-refresh-contents)) \
              (dolist (pkg '(package-lint)) \
                (unless (package-installed-p pkg) \
                  (package-install pkg))) \
              (require 'package-lint))" \
              -f package-lint-batch-and-exit ox-s9y.el

jobs:
  emacs_27:
    docker:
      - image: silex/emacs:27
    steps:
      - testsuite

  emacs_26:
    docker:
      - image: silex/emacs:26
    steps:
      - testsuite

  emacs_25:
    docker:
      - image: silex/emacs:25
    steps:
      - testsuite

workflows:
  version: 2
  commit:
    jobs:
      - emacs_25
      - emacs_26
      - emacs_27
  monthly:
    triggers:
      - schedule:
          cron: "42 23 6 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - emacs_25
      - emacs_26
      - emacs_27
