---
version: 2.1
commands:
  testsuite:
    steps:
      - checkout
      - run:
          name: Log Emacs Version
          command: emacs --version
      - run:
          name: Log Org Version
          command: emacs -Q --batch -f org-version
      - run:
          name: Byte compilation
          command: emacs -Q --batch -f batch-byte-compile ox-s9y.el
      - run:
          name: Tests
          command: emacs -Q --batch -l ert -l ox-s9y.elc -l testing/test-ox-s9y.el -f ert-run-tests-batch-and-exit

jobs:
  emacs_27:
    docker:
      - image: silex/emacs:27
    steps:
      - testsuite

  emacs_26:
    docker:
      - image: silex/emacs:26
    steps:
      - testsuite

  emacs_25:
    docker:
      - image: silex/emacs:25
    steps:
      - checkout

workflows:
  version: 2
  commit:
    jobs:
      - emacs_25
      - emacs_26
      - emacs_27
  monthly:
    triggers:
      - schedule:
          cron: "42 23 6 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - emacs_25
      - emacs_26
      - emacs_27
